# Generated by Django 3.2.25 on 2025-07-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_alter_batch_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
