# Generated by Django 3.2.25 on 2025-07-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_alter_batch_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
