# Generated by Django 3.2.25 on 2025-07-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_request', '0002_alter_supplier_managed_by'),
        ('inventory_management', '0005_auto_20250705_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='suppliers',
            field=models.ManyToManyField(related_name='medicines', through='medicine_request.SupplierMedicine', to='medicine_request.Supplier'),
        ),
    ]
