# Generated by Django 3.2.25 on 2025-07-10 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='managed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
