# Generated by Django 3.2.25 on 2025-06-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_username'),
    ]

    operations = [
    ]
